from backend.models.schemas import EmailSummary


def build_email_summary_card(summary: EmailSummary, generated_by: str) -> dict:
    body: list[dict] = [
        {
            "type": "TextBlock",
            "text": "Today's Email Summary",
            "weight": "Bolder",
            "size": "Large",
            "wrap": True,
        },
        {
            "type": "TextBlock",
            "text": f"{len(summary.important)} important · {len(summary.normal)} informational",
            "isSubtle": True,
            "spacing": "Small",
            "wrap": True,
        },
    ]

    if not summary.important and not summary.normal:
        body.append({"type": "TextBlock", "text": "No unread emails found.", "wrap": True})

    if summary.important:
        body.append(
            {
                "type": "TextBlock",
                "text": "Important & action required",
                "weight": "Bolder",
                "spacing": "Large",
                "wrap": True,
            }
        )
        for item in summary.important:
            body.extend(_summary_item(item.subject, item.summary, item.action, "Attention"))

    if summary.normal:
        body.append(
            {
                "type": "TextBlock",
                "text": "Information only",
                "weight": "Bolder",
                "spacing": "Large",
                "wrap": True,
            }
        )
        for item in summary.normal:
            body.extend(_summary_item(item.subject, item.summary, item.action, "Default"))

    body.append(
        {
            "type": "TextBlock",
            "text": f"Generated by {generated_by}",
            "isSubtle": True,
            "size": "Small",
            "spacing": "Large",
            "wrap": True,
        }
    )
    return {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.4",
        "body": body,
    }


def _summary_item(subject: str, summary: str, action: str, color: str) -> list[dict]:
    blocks = [
        {
            "type": "TextBlock",
            "text": subject,
            "weight": "Bolder",
            "color": color,
            "spacing": "Medium",
            "wrap": True,
        },
        {"type": "TextBlock", "text": summary, "spacing": "Small", "wrap": True},
    ]
    if action:
        blocks.append(
            {
                "type": "TextBlock",
                "text": f"**Recommended action:** {action}",
                "spacing": "Small",
                "wrap": True,
            }
        )
    return blocks

